#!/bin/bash
#
# run_now.sh - Execute the current test
#
# This file is regenerated by Claude Code each time a test needs to run.
# Just execute: ./run_now.sh
#
# Current test: SD_Test_Suite (SD Card FAT32 Driver Validation)
#

../tools/run_test.sh SD_Test_Suite "$(dirname "$0")" -t 120
